variables:
  UPDATE_REPO: "git@github.com:techart/image-service.git"
include:
  - project: "libs/cicd-includes"
    file: "/templates/.gitlab-ci-packagist.yml"
testing:
  stage: test
  tags:
    - ssh
    - php82
  script:
    - |
      pwd
      composer install && composer test